// Generated by dia2code
#ifndef CONTROL__CLAVIER__H
#define CONTROL__CLAVIER__H


namespace control {

  /// class Clavier - 
  class Clavier {
    // Operations
  public:
    Clavier ();
    ~Clavier ();
    void gestion_clavier ();
  };

};

#endif
