// Generated by dia2code
#ifndef CONTROL__CLAVIER__H
#define CONTROL__CLAVIER__H


namespace state {
  class State;
};
namespace control {
  class Observable;
}

#include "Observable.h"

namespace control {

  /// class Clavier - 
  class Clavier : public control::Observable {
    // Operations
  public:
    Clavier ();
    ~Clavier ();
    void gestion_clavier (state::State& state);
  };

};

#endif
