// Generated by dia2code
#ifndef CONTROL__CLOCK__H
#define CONTROL__CLOCK__H

#include <SFML/Graphics.hpp>

namespace state {
  class Element;
}

#include "state/Element.h"

namespace control {

  /// class Clock - 
  class Clock {
    // Attributes
  public:
    sf::Clock clock;
    // Operations
  public:
    Clock ();
    ~Clock ();
    void  action (state::Element element);
  };

};

#endif
