// Generated by dia2code
#ifndef CONTROL__SOURIS__H
#define CONTROL__SOURIS__H

#include <SFML/Graphics.hpp>

namespace state {
  class ListElement;
  class Player;
};
namespace control {
  class Observable;
}

#include "state/ListElement.h"
#include "state/Player.h"
#include "Observable.h"

namespace control {

  /// class Souris - 
  class Souris : public control::Observable {
    // Attributes
  public:
    int* posX;
    int* posY;
    // Operations
  public:
    Souris ();
    ~Souris ();
    state::ListElement gestion_souris (state::ListElement list_element, state::Player player, int mode);
    void Update (sf::RenderWindow& window);
  };

};

#endif
