// Generated by dia2code
#ifndef CONTROL__SOURIS__H
#define CONTROL__SOURIS__H

#include <SFML/Graphics.hpp>

class Observable;
#include "Observable.h"

namespace control {

  /// class Souris - 
  class Souris : public Observable {
    // Attributes
  public:
    int* mouseX;
    int* mouseY;
    int* left;
    int* frontDesc;
    // Operations
  public:
    Souris ();
    ~Souris ();
    void gestion_souris (sf::RenderWindow& window);
  };

};

#endif
