// Generated by dia2code
#ifndef ENGINE__CLAVIER__H
#define ENGINE__CLAVIER__H

#include <state/Element.h>

namespace state {
  class State;
}

namespace engine {

  /// class Clavier - 
  class Clavier {
    // Operations
  public:
    Clavier ();
    ~Clavier ();
    void gestion_clavier (state::State& state, sf::Keyboard::Key key);
  };

};

#endif
