// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <state/Element.h>

namespace state {
  class State;
}

namespace engine {

  // abstract
  /// class Command - 
  class Command {
    // Operations
  public:
    virtual void make (state::State& state) = 0;
    Command ();
    ~Command ();
  };

};

#endif
