// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <state/Element.h>

namespace engine {
  class Move_unit;
};
namespace state {
  class State;
}

#include "Move_unit.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Attributes
  public:
    engine::Move_unit action;
    // Operations
  public:
    Engine ();
    ~Engine ();
    void Update (state::State& state);
  };

};

#endif
