// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>
#include <state/Element.h>

namespace engine {
  class Move_unit;
};
namespace state {
  class State;
};
namespace ihm {
  class Player;
}

#include "Move_unit.h"
#include "ihm/Player.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Attributes
  public:
    std::vector<int> list_gang;
    int round;
    std::vector<engine::Move_unit> list_action;
    // Operations
  public:
    Engine ();
    ~Engine ();
    void Update (state::State& state, ihm::Player player);
  };

};

#endif
