// Generated by dia2code
#ifndef ENGINE__FIFO__H
#define ENGINE__FIFO__H

#include <vector>
#include <mutex>
#include <state/Element.h>

namespace engine {
  class Command;
};
namespace state {
  class State;
};
namespace engine {
  class Engine;
}

#include "Engine.h"

namespace engine {

  /// class Fifo - 
  class Fifo {
    // Attributes
  public:
    std::vector<engine::Command*> list_commande;
    std::mutex mutex;
    // Operations
  public:
    void write (state::State& state, engine::Command* command);
    void read (state::State& state);
    Fifo ();
    ~Fifo ();
  };

};

#endif
