// Generated by dia2code
#ifndef ENGINE__RECORD__H
#define ENGINE__RECORD__H

#include <vector>

namespace engine {
  class Move_unit;
  class Engine;
}

#include "Move_unit.h"
#include "Engine.h"

namespace engine {

  /// class Record - 
  class Record {
    // Associations
    // Attributes
  public:
    std::vector<engine::Move_unit> list_commande;
    // Operations
  public:
    Record ();
    ~Record ();
  };

};

#endif
