// Generated by dia2code
#ifndef ENGINE__SOURIS__H
#define ENGINE__SOURIS__H

#include <state/Element.h>

namespace state {
  class ListElement;
  class Player;
}

#include "state/ListElement.h"
#include "state/Player.h"

namespace engine {

  /// class Souris - 
  class Souris {
    // Attributes
  public:
    int* posX;
    int* posY;
    // Operations
  public:
    Souris ();
    ~Souris ();
    state::ListElement gestion_souris (state::ListElement list_element, state::Player player, int mode);
    void Update (sf::RenderWindow& window);
  };

};

#endif
