// Generated by dia2code
#ifndef IHM__CLAVIER__H
#define IHM__CLAVIER__H

#include <state/Element.h>

namespace state {
  class State;
};
namespace ihm {
  class Player;
}

#include "Player.h"

namespace ihm {

  /// class Clavier - 
  class Clavier {
    // Operations
  public:
    Clavier ();
    ~Clavier ();
    void gestion_clavier (const state::State& state, sf::Keyboard::Key key, ihm::Player player);
  };

};

#endif
