// Generated by dia2code
#ifndef IHM__PLAYER__H
#define IHM__PLAYER__H

#include <state/Element.h>

namespace state {
  class Gang;
  class Element;
  class State;
}

#include "state/Gang.h"

namespace ihm {

  /// class Player - 
  class Player {
    // Attributes
  public:
    int* view_posX;
    int* view_posY;
    state::Gang gang;
    state::Element* tour_cliked;
    int* tour_unit_pris;
  private:
    int* compteur;
    int* chiffre_pris;
    int* state;
    // Operations
  public:
    Player ();
    ~Player ();
    void Update (const state::State& state);
    int getCompteur ();
    void setCompteur (int compteur);
    int get_chiffre_pris ();
    void set_chiffre_pris (int chiffre_pris);
    int get_state () const;
    void set_state (int state);
  };

};

#endif
