// Generated by dia2code
#ifndef IHM__SOURIS__H
#define IHM__SOURIS__H

#include <state/Element.h>

namespace state {
  class ListElement;
};
namespace ihm {
  class Player;
}

#include "state/ListElement.h"
#include "Player.h"

namespace ihm {

  /// class Souris - 
  class Souris {
    // Attributes
  public:
    int* posX;
    int* posY;
    // Operations
  public:
    Souris ();
    ~Souris ();
    state::ListElement gestion_souris (const state::ListElement list_element, ihm::Player player, int mode);
    void Update (sf::RenderWindow& window);
  };

};

#endif
