// Generated by dia2code
#ifndef IA__DEFENCE__H
#define IA__DEFENCE__H

#include <vector>
#include <state/Element.h>

namespace engine {
  class Move_unit;
};
namespace state {
  class State;
}

#include "engine/Move_unit.h"

namespace ia {

  /// class Defence - 
  class Defence {
    // Attributes
  public:
    std::vector<engine::Move_unit> list_defence;
    std::vector<int> list_score;
    // Operations
  public:
    int score_defence (state::State& state);
    Defence ();
    ~Defence ();
    void init (state::State& state, int gang);
  };

};

#endif
