// Generated by dia2code
#ifndef IA__IA__H
#define IA__IA__H

#include <state/Element.h>

namespace state {
  class State;
}

namespace ia {

  /// class IA - 
  class IA {
    // Operations
  public:
    IA ();
    ~IA ();
    void play (state::State& state);
  };

};

#endif
