// Generated by dia2code
#ifndef IA__NODE__H
#define IA__NODE__H


namespace ia {
  class MinMax;
}

#include "MinMax.h"

namespace ia {

  /// class Node - 
  class Node {
    // Attributes
  public:
    int depth;
    int gang;
    int width;
    int nb_child;
  private:
    int* score;
    int* ind_sol;
    // Operations
  public:
    Node ();
    ~Node ();
    Node (int depth);
    Node (int depth, int width, int gang);
    int get_ind_sol ();
    int get_score ();
    void set_score (int score);
    void set_ind_sol (int ind_sol);
  };

};

#endif
