// Generated by dia2code
#ifndef STATE__ADJACENT__H
#define STATE__ADJACENT__H


namespace state {
  class Territory;
}

namespace state {

  /// class Adjacent - 
  class Adjacent {
    // Attributes
  private:
    Territory* territory_1;
    Territory* territory_2;
    // Operations
  public:
    Adjacent (Territory* territory_1, Territory* territory_2);
    ~Adjacent ();
    Territory* get_territory_1 ();
    Territory* get_territory_2 ();
    void set_territory_1 (Territory* territory_1);
    void set_territory_2 (Territory* territory_2);
  };

};

#endif
