// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {

  /// class Element - 
  class Element {
    // Attributes
  public:
    int territory;
  private:
    int* statut;
  protected:
    int* posX;
    int type;
    int* posY;
    // Operations
  public:
    Element ();
    ~Element ();
    int getType () const;
    void setType (int type);
    int getPosX () const;
    int getPosY () const;
    void setPosX (int posX, int posY);
    Element (int posX, int posY, int type);
    Element (int posX, int posY, int type, int statut);
    bool isClickable ();
    bool isChiffre ();
    Element (int posX, int posY, int type, int statut, int territory);
    int getStatut () const;
    void setStatut (int statut);
  };

};

#endif
