// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H

#include <SFML/Graphics.hpp>
#include <string>

namespace renderer {
  class Texture;
}

#include "renderer/Texture.h"

namespace state {

  /// class Element - 
  class Element {
    // Attributes
  public:
    sf::Vector2f pos;
    sf::Sprite sprite;
    std::string path;
    renderer::Texture texture;
    sf::Vector2f scale;
    // Operations
  public:
    Element ();
    Element (std::string path, sf::Vector2f pos, sf::Vector2f scale);
    ~Element ();
    void init ();
  };

};

#endif
