// Generated by dia2code
#ifndef STATE__GANG__H
#define STATE__GANG__H

#include <string>
#include <vector>

namespace state {

  /// class Gang - 
  class Gang {
    // Attributes
  public:
    int ID;
  private:
    int* money;
    int nb_card_gang;
    bool alive;
    std::string name;
    std::vector<int> list_territory;
    int* action_done;
    int* turn;
    // Operations
  public:
    Gang ();
    ~Gang ();
    void set_nb_card_gang (int nb_card_gang);
    int get_nb_card_gang ();
    void set_money (int money);
    int get_money ();
    void set_alive (bool alive);
    bool get_alive ();
    std::string get_name ();
    void set_name (std::string name);
    void setListTerritory (std::vector<int> list_territory);
    std::vector<int> getListTerritory ();
    int getTurn ();
    void setTurn (int turn);
    int getAction_done ();
    void setAction_done (int nb);
  };

};

#endif
