// Generated by dia2code
#ifndef STATE__GRAPH__H
#define STATE__GRAPH__H

#include <vector>

namespace state {
  class Territory;
  class Adjacent;
}

#include "Adjacent.h"
#include "Territory.h"

namespace state {

  /// class Graph - 
  class Graph {
    // Associations
    // Attributes
  private:
    std::vector<Territory*> list_summit;
    std::vector<Adjacent*> list_adjacent;
    // Operations
  public:
    Graph (Territory* summit, Adjacent* adjacent);
    ~Graph ();
    void add_summit (Territory* summit);
    void delete_summit (Territory* summit);
    void delete_adjacent (Territory* territory_1, Territory* territory_2);
    void add_adjacent (Adjacent* adjacent);
  };

};

#endif
