// Generated by dia2code
#ifndef STATE__GRAPH__H
#define STATE__GRAPH__H

#include <vector>

namespace state {
  class Adjacent;
  class Territory;
}

#include "Adjacent.h"
#include "Territory.h"

namespace state {

  /// class Graph - 
  class Graph {
    // Associations
    // Attributes
  private:
    std::vector<Summit*> list_summit;
    std::vector<Adjacent*> list_adjacent;
    // Operations
  public:
    Graph ();
    ~Graph ();
    Graph* const clone ();
    add_summit (Territory* summit);
    delete_summit (int ID);
    delete_adjacent (int ID_1, int ID_2);
    add_adjacent (Adjacent* adjacent);
  };

};

#endif
