// Generated by dia2code
#ifndef STATE__IOBSERVATEUR__H
#define STATE__IOBSERVATEUR__H


namespace control {
  class Observable;
}

#include "control/Observable.h"

namespace state {

  /// class IObservateur - 
  class IObservateur {
    // Associations
    // Operations
  public:
    void notifier ();
  };

};

#endif
