// Generated by dia2code
#ifndef STATE__LISTELEMENT__H
#define STATE__LISTELEMENT__H

#include <state/Element.h>
#include <vector>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class ListElement - 
  class ListElement {
    // Associations
    // Attributes
  private:
    std::vector<state::Element> list_element;
    int size;
    int id_view;
    // Operations
  public:
    ListElement (int id_view);
    ~ListElement ();
    void add_element (state::Element element);
    std::vector<state::Element> getlist ();
    int getSize ();
    int getIdView ();
    void setIdView (int id_view);
  };

};

#endif
