// Generated by dia2code
#ifndef STATE__LISTELEMENT__H
#define STATE__LISTELEMENT__H

#include <vector>
#include <SFML/Graphics.hpp>

namespace state {
  class Element;
  class ListTerritory;
  class State;
};
namespace control {
  class Souris;
}

#include "Element.h"
#include "ListTerritory.h"
#include "State.h"
#include "control/Souris.h"

namespace state {

  /// class ListElement - 
  class ListElement {
    // Associations
    // Attributes
  private:
    std::vector<state::Element> list_element;
    int size;
    // Operations
  public:
    ListElement ();
    ~ListElement ();
    void add_element (state::Element element);
    state::Element* getlist ();
    int getSize ();
    void init ();
    void draw (sf::RenderWindow& window, state::ListTerritory list_territory, state::State state);
    void upDate (control::Souris souris, sf::RenderWindow& window, sf::View view, state::ListTerritory list_territory);
  };

};

#endif
