// Generated by dia2code
#ifndef STATE__LISTTERRITORY__H
#define STATE__LISTTERRITORY__H

#include <vector>
#include <SFML/Graphics.hpp>

namespace state {
  class Territory;
};
namespace control {
  class Souris;
};
namespace state {
  class State;
}

#include "Territory.h"
#include "control/Souris.h"
#include "State.h"

namespace state {

  /// class ListTerritory - 
  class ListTerritory {
    // Associations
    // Attributes
  public:
    std::vector<state::Territory> list_territory;
    int cliked;
    // Operations
  public:
    ListTerritory ();
    ~ListTerritory ();
    void Update (control::Souris souris, sf::RenderWindow& window, sf::View view);
    void draw (sf::RenderWindow& window);
    void init ();
  };

};

#endif
