// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <SFML/Graphics.hpp>

namespace state {

  /// class Player - 
  class Player {
    // Attributes
  private:
    sf::Vector2f* pos;
    // Operations
  public:
    Player ();
    ~Player ();
    void setPos (sf::Vector2f pos);
    sf::Vector2f getPos ();
  };

};

#endif
