// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <vector>

namespace state {
  class Player;
  class Territory;
  class ListElement;
  class Gang;
  class IObservateur;
}

#include "Player.h"
#include "Territory.h"
#include "ListElement.h"
#include "Gang.h"
#include "IObservateur.h"
#include "STATE.h"

namespace state {

  /// class State - 
  class State : public state::IObservateur {
    // Associations
    // Attributes
  public:
    state::Player player;
    std::vector<state::Territory> list_territory;
  private:
    int* state;
    std::vector<state::ListElement> list_ListElement;
    std::vector<Gang> list_gang;
    // Operations
  public:
    State ();
    ~State ();
    int getState ();
    void setState (int state);
    std::vector<ListElement> getListListElement ();
    void add_ListElement (state::ListElement ListElement);
    std::vector<Gang> getListGang ();
    void add_Gang (state::Gang Gang);
    void upDate ();
    void init ();
    void notifier ();
  };

};

#endif
