// Generated by dia2code
#ifndef STATE__STATE_CLICKABLE__H
#define STATE__STATE_CLICKABLE__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  enum STATE_CLICKABLE {
    uncliked     = 0,
    cliked     = 1
  };

};

#endif
