// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class Graph;
}

#include "Graph.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  public:
    int Mode;
    int nb_territory;
    int nb_gang;
    // Operations
  public:
    State ();
    ~State ();
    int get_nb_territory ();
    void set_nb_territory (int nb_territory);
    int get_nb_gang ();
    void set_nb_gang (int nb_gang);
  };

};

#endif
