// Generated by dia2code
#ifndef STATE__TERRITORY__H
#define STATE__TERRITORY__H

#include <string>

namespace state {
  class Gang;
}

#include "Gang.h"

namespace state {

  /// class Territory - 
  class Territory {
    // Associations
    // Attributes
  private:
    int nb_unit;
    std::string gang;
    int ID;
    bool QG;
    // Operations
  public:
    Territory ();
    ~Territory ();
    int get_nb_unit ();
    void set_nb_unit (int nb_unit);
    std::string get_gang ();
    void set_gang (std::string gang);
    int get_ID ();
    void set_ID (int ID);
    bool get_QG ();
    void set_QG (bool boolean_QG);
  };

};

#endif
