// Generated by dia2code
#ifndef STATE__TERRITORY__H
#define STATE__TERRITORY__H

#include <vector>

namespace state {

  /// class Territory - 
  class Territory {
    // Attributes
  private:
    int* nb_unit;
    int* gang;
    int ID;
    bool QG;
    std::vector<int> Adjacent;
    // Operations
  public:
    Territory ();
    ~Territory ();
    int get_nb_unit ();
    void set_nb_unit (int nb_unit);
    int get_gang ();
    void set_gang (int gang);
    int get_ID ();
    void set_ID (int ID);
    bool get_QG ();
    void set_QG (bool boolean_QG);
    std::vector<int> getAdajcent ();
    void addAdjacent (int adjacent);
    Territory (int nb_unit, int Id, bool QG, int owner);
  };

};

#endif
