// Generated by dia2code
#ifndef STATE__TERRITORY__H
#define STATE__TERRITORY__H

#include <string>

namespace state {
  class Gang;
  class Adjacent;
}

#include "Gang.h"
#include "Adjacent.h"

namespace state {

  /// class Territory - 
  class Territory {
    // Associations
    // Attributes
  private:
    int nb_unit;
    std::string gang;
    int Id;
    bool QG;
    // Operations
  public:
    Territory ();
    ~Territory ();
    Territory* const clone ();
    int get_nb_unit ();
    set_nb_unit (int nb_unit);
    std::string get_gang ();
    set_gang (string gang);
    int get_ID ();
    set_ID (int ID);
    bool get_QG ();
    set_QG (bool boolean_QG);
  };

};

#endif
