// Generated by dia2code
#ifndef STATE__TYPE__H
#define STATE__TYPE__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  enum TYPE {
    plage_menu_type     = 1,
    carte_verso_type     = 2,
    soldat_type     = 3,
    plage_commune_type     = 4,
    chiffre_unite_type     = 5,
    chiffre_dizaine_type     = 6,
    chiffre_centaine_type     = 7,
    chiffre_millier_type     = 8,
    plage_carte_A_type     = 9,
    plage_carte_B_type     = 10,
    plage_carte_C_type     = 11,
    background_type     = 12,
    button_ok_compteur_type     = 13,
    button_add_type     = 14,
    button_minus_type     = 15,
    tour_type     = 16,
    money_type     = 17,
    logo_boutique_type     = 18,
    prix_unite_type     = 19,
    prix_dizaine_type     = 20,
    prix_centaine_type     = 21,
    button_ok_A_type     = 22,
    button_ok_B_type     = 23,
    button_ok_C_type     = 24
  };

};

#endif
