// Generated by dia2code
#ifndef STATE__VIEW__H
#define STATE__VIEW__H


namespace state {
  class ListElement;
}

#include "ListElement.h"

namespace state {

  enum VIEW {
    list_boutique     = 1,
    list_plage_menu     = 2,
    list_map     = 3,
    list_minimap     = 4,
    list_plage_commune     = 5
  };

};

#endif
