// Generated by dia2code
#ifndef __RENDERER__H
#define __RENDERER__H

#include "renderer/Textures.h"
#include "renderer/Tile.h"
#include "renderer/View.h"
#include "renderer/Render.h"
#include "renderer/TYPE_VIEW.h"
#include "renderer/Animation.h"
#endif
