// Generated by dia2code
#ifndef RENDERER__ANIMATION__H
#define RENDERER__ANIMATION__H

#include <SFML/Graphics.hpp>
#include <vector>

namespace state {
  class ListElement;
};
namespace ihm {
  class Player;
};
namespace state {
  class Territory;
};
namespace renderer {
  class View;
}

#include "state/ListElement.h"
#include "state/Territory.h"
#include "View.h"

namespace renderer {

  /// class Animation - 
  class Animation {
    // Operations
  public:
    Animation ();
    ~Animation ();
    std::vector<sf::Sprite> Update (std::vector<sf::Sprite> list_sprite, const state::ListElement list_element, ihm::Player& player, const std::vector<state::Territory> list_territory);
    sf::Sprite affiche_chiffre (int chiffre, sf::Sprite& sprite);
  };

};

#endif
