// Generated by dia2code
#ifndef RENDERER__LEVEL__H
#define RENDERER__LEVEL__H


namespace renderer {
  class Window;
};
namespace state {
  class State;
};
namespace renderer {
  class View;
}

#include "Window.h"
#include "state/State.h"
#include "View.h"

namespace renderer {

  /// class Level - 
  class Level {
    // Attributes
  public:
    renderer::Window window;
    state::State state;
    // Operations
  public:
    Level ();
    ~Level ();
    void level_init ();
    void upDate ();
  };

};

#endif
