// Generated by dia2code
#ifndef RENDERER__LEVEL__H
#define RENDERER__LEVEL__H

#include <SFML/Graphics.hpp>

namespace renderer {
  class Window;
  class Texture;
}

#include "Window.h"
#include "Texture.h"

namespace renderer {

  /// class Level - 
  class Level {
    // Associations
    // Attributes
  public:
    sf::Sprite sprite_perso;
    sf::Sprite sprite_plage_commune;
    sf::Sprite sprite_background;
    sf::Sprite sprite_money;
    sf::Sprite sprite_plage_carte_A;
    sf::Sprite sprite_plage_carte_B;
    sf::Sprite sprite_plage_carte_C;
    sf::Sprite sprite_logo_boutique;
    sf::Sprite sprite_carte_verso_A;
    sf::Sprite sprite_carte_verso_B;
    sf::Sprite sprite_carte_verso_C;
    sf::Sprite sprite_button_add;
    sf::Sprite sprite_button_minus;
    sf::Sprite sprite_button_ok_A;
    sf::Sprite sprite_button_ok_B;
    sf::Sprite sprite_button_ok_C;
    sf::Sprite sprite_button_ok_compteur;
    sf::Sprite sprite_soldat;
    sf::Sprite sprite_chiffre_unite;
    sf::Sprite sprite_chiffre_dizaine;
    sf::Sprite sprite_prix_unite;
    sf::Sprite sprite_prix_dizaine;
    sf::Sprite sprite_prix_centaine;
    sf::Sprite sprite_plage_menu;
    sf::Sprite sprite_tour;
    renderer::Window window;
    // Operations
  public:
    Level ();
    ~Level ();
    void level_init ();
    void upDate ();
  };

};

#endif
