// Generated by dia2code
#ifndef RENDERER__RENDER__H
#define RENDERER__RENDER__H

#include <SFML/Graphics.hpp>
#include <vector>

namespace renderer {
  class View;
};
namespace state {
  class State;
}

#include "View.h"
#include "state/State.h"

namespace renderer {

  /// class Render - 
  class Render {
    // Associations
    // Attributes
  public:
    sf::RenderWindow window;
    std::vector<renderer::View> list_view;
    // Operations
  public:
    ~Render ();
    void init (state::State state_game);
    void draw (state::State state_game);
    Render ();
    void upDate (state::State state_game);
  };

};

#endif
