// Generated by dia2code
#ifndef RENDERER__RENDER__H
#define RENDERER__RENDER__H

#include <SFML/Graphics.hpp>
#include <vector>

namespace renderer {

  /// class Render - 
  class Render {
    // Attributes
  public:
    std::vector<sf::Sprite> list_element_boutique;
    std::vector<sf::Sprite> list_element_plage_menu;
    std::vector<sf::Sprite> list_element_minimap;
    std::vector<sf::Sprite> list_element_plage_commune;
    // Operations
  public:
    Render ();
    ~Render ();
    void add_element (sf::Sprite& element, std::vector<sf::Sprite> list);
    void remove_element (std::vector<sf::Sprite> list);
  };

};

#endif
