// Generated by dia2code
#ifndef RENDERER__TEXTURES__H
#define RENDERER__TEXTURES__H

#include <SFML/Graphics.hpp>

namespace state {
  class Element;
}

#include "state/Element.h"

namespace renderer {

  /// class Textures - 
  class Textures {
    // Attributes
  public:
    sf::Sprite sprite;
    sf::Texture texture;
    // Operations
  public:
    Textures ();
    ~Textures ();
    void load_texture (state::Element element);
  };

};

#endif
