// Generated by dia2code
#ifndef RENDERER__TYPE_VIEW__H
#define RENDERER__TYPE_VIEW__H


namespace renderer {

  enum TYPE_VIEW {
    view_boutique     = 1,
    view_minimap     = 2,
    view_plage     = 3,
    view_map     = 4,
    view_plage_commune     = 5
  };

};

#endif
