// Generated by dia2code
#ifndef RENDERER__VIEW__H
#define RENDERER__VIEW__H

#include <SFML/Graphics.hpp>

namespace state {
  class State;
};
namespace renderer {
  class Level;
}

#include "state/State.h"
#include "Level.h"

namespace renderer {

  /// class View - 
  class View {
    // Attributes
  public:
    sf::View view_boutique;
    sf::View view_plage_commune;
    sf::View view_map;
    sf::View view_menu;
    sf::View view_minimap;
    sf::RectangleShape rectangle;
    // Operations
  public:
    View ();
    ~View ();
    void View_init (state::State state);
    void View_UpDate (state::State state);
  };

};

#endif
