// Generated by dia2code
#ifndef RENDERER__VIEW__H
#define RENDERER__VIEW__H

#include <SFML/Graphics.hpp>

namespace renderer {

  /// class View - 
  class View {
    // Attributes
  public:
    sf::View view_boutique;
    sf::View view_plage_commune;
    sf::View view_map;
    sf::View view_menu;
    sf::View view_minimap;
    // Operations
  public:
    View ();
    ~View ();
    void View_init ();
  };

};

#endif
