// Generated by dia2code
#ifndef RENDERER__VIEW__H
#define RENDERER__VIEW__H

#include <SFML/Graphics.hpp>
#include <vector>

namespace renderer {
  class Textures;
};
namespace state {
  class State;
}

#include "Textures.h"
#include "state/State.h"

namespace renderer {

  /// class View - 
  class View {
    // Associations
    // Attributes
  public:
    sf::View view;
    int type;
    std::vector<sf::Sprite> list_sprite;
    std::vector<renderer::Textures> list_texture;
    // Operations
  public:
    View (int view);
    ~View ();
    void View_init (state::State& state);
    void draw (sf::RenderWindow& window, int mode);
    void add_Sprite (sf::Sprite sprite);
    void View_upDate (state::State state);
  };

};

#endif
