// Generated by dia2code
#ifndef RENDERER__WINDOW__H
#define RENDERER__WINDOW__H

#include <SFML/Graphics.hpp>

namespace renderer {

  /// class Window - 
  class Window {
    // Attributes
  public:
    sf::RenderWindow window;
    // Operations
  public:
    Window ();
    ~Window ();
    void Window_init ();
  };

};

#endif
